/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BracketGroup {
  'size' : number,
  'take_profit_price' : number,
  'sl_modified_by_user' : boolean,
  'bracket_id' : string,
  'stop_loss_price' : number,
}
export interface BracketOrder {
  'bracket_groups' : Array<BracketGroup>,
  'primary_stop_loss' : number,
  'calculation_method' : string,
  'position_sizer' : PositionSizer,
  'position_size' : number,
  'entry_price' : number,
  'value_per_unit' : number,
}
export interface BracketOrderOutcome {
  'rr' : number,
  'final_pl_pct' : number,
  'final_pl_usd' : number,
  'filled_bracket_groups' : Array<FilledBracketGroup>,
}
export type CalculationMethod = { 'tick' : null } |
  { 'point' : null };
export type ClosureType = { 'take_profit' : null } |
  { 'manual_close' : null } |
  { 'stop_loss' : null } |
  { 'break_even' : null };
export interface CustomProperty {
  'id' : string,
  'type' : PropertyType,
  'propertyLabel' : string,
  'options' : Array<string>,
  'default_value' : string,
}
export interface CustomToolDefinition {
  'id' : string,
  'updated_at' : bigint,
  'owner' : Principal,
  'name' : string,
  'properties' : Array<CustomProperty>,
  'created_at' : bigint,
}
export interface FilledBracketGroup {
  'manual_close_price' : [] | [number],
  'break_even_applied' : boolean,
  'closure_price' : number,
  'size' : number,
  'break_even_price' : [] | [number],
  'bracket_id' : string,
  'manual_close_applied' : boolean,
  'closure_type' : ClosureType,
}
export interface Model {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'framework' : Array<ToolConfig>,
  'description' : string,
  'created_at' : bigint,
  'narrative' : Array<ToolConfig>,
  'execution' : Array<ToolConfig>,
}
export interface ModelCondition {
  'id' : string,
  'isChecked' : boolean,
  'zone' : string,
  'description' : string,
}
export interface PositionSizer {
  'contract_lot_unit' : string,
  'allow_fractional_size' : boolean,
  'asset_type' : string,
  'account_capital' : number,
  'value_per_point' : number,
  'primary_stop_loss' : number,
  'risk_percentage' : number,
  'entry_price' : number,
}
export type PropertyType = { 'text' : null } |
  { 'select' : null } |
  { 'toggle' : null } |
  { 'number' : null };
export interface ToolConfig {
  'id' : string,
  'type' : string,
  'zone' : string,
  'properties' : string,
  'actions' : Array<string>,
  'interactions' : Array<string>,
  'position' : bigint,
}
export interface Trade {
  'id' : string,
  'direction' : string,
  'asset' : string,
  'owner' : Principal,
  'model_conditions' : Array<ModelCondition>,
  'created_at' : bigint,
  'bracket_order_outcome' : BracketOrderOutcome,
  'calculation_method' : CalculationMethod,
  'is_completed' : boolean,
  'position_sizer' : PositionSizer,
  'notes' : string,
  'adherence_score' : number,
  'emotions' : Array<string>,
  'model_id' : string,
  'bracket_order' : BracketOrder,
  'value_per_unit' : number,
  'images' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateAdherenceScore' : ActorMethod<[Array<ModelCondition>], number>,
  'createCustomTool' : ActorMethod<[CustomToolDefinition], string>,
  'createModel' : ActorMethod<[Model], undefined>,
  'createTrade' : ActorMethod<[Trade], undefined>,
  'deleteCustomTool' : ActorMethod<[string], string>,
  'deleteModel' : ActorMethod<[string], undefined>,
  'deleteTrade' : ActorMethod<[string], undefined>,
  'duplicateCustomTool' : ActorMethod<[string, string], string>,
  'getAdherenceAnalytics' : ActorMethod<
    [],
    {
      'avg_adherence' : number,
      'total_trades' : bigint,
      'win_rate_high_adherence' : number,
      'win_rate_low_adherence' : number,
    }
  >,
  'getAllCustomTools' : ActorMethod<[], Array<CustomToolDefinition>>,
  'getAllModels' : ActorMethod<[], Array<Model>>,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentTime' : ActorMethod<[], bigint>,
  'getCustomTool' : ActorMethod<[string], [] | [CustomToolDefinition]>,
  'getCustomToolCount' : ActorMethod<[], bigint>,
  'getModel' : ActorMethod<[string], [] | [Model]>,
  'getModelConditions' : ActorMethod<[string], Array<ModelCondition>>,
  'getTotalAllocation' : ActorMethod<[Array<BracketGroup>], number>,
  'getTrade' : ActorMethod<[string], [] | [Trade]>,
  'getTradesByAdherenceRange' : ActorMethod<[number, number], Array<Trade>>,
  'getTradesByAsset' : ActorMethod<[string], Array<Trade>>,
  'getTradesByDateRange' : ActorMethod<[bigint, bigint], Array<Trade>>,
  'getTradesByModel' : ActorMethod<[string], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mapTradeConditionsToModel' : ActorMethod<
    [Array<ModelCondition>, Array<ModelCondition>],
    Array<ModelCondition>
  >,
  'saveBracketOrderOutcome' : ActorMethod<
    [string, BracketOrderOutcome],
    {
      'updatedTrade' : Trade,
      'updatedAnalytics' : {
        'totalTrades' : number,
        'avgPL' : number,
        'avgRR' : number,
        'totalPL' : number,
        'totalRR' : number,
        'totalWins' : number,
        'bracketOrderValidation' : { 'valid' : null } |
          { 'invalid_take_profit_order' : null } |
          { 'invalid_event_combination' : null } |
          { 'invalid_stop_loss_adjustment' : null },
        'winRate' : number,
      },
    }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomTool' : ActorMethod<[CustomToolDefinition], string>,
  'updateModel' : ActorMethod<[Model], undefined>,
  'updateModelAnalytics' : ActorMethod<
    [string],
    {
      'totalTrades' : number,
      'avgPL' : number,
      'avgRR' : number,
      'totalPL' : number,
      'totalRR' : number,
      'totalWins' : number,
      'bracketOrderValidation' : { 'valid' : null } |
        { 'invalid_take_profit_order' : null } |
        { 'invalid_event_combination' : null } |
        { 'invalid_stop_loss_adjustment' : null },
      'winRate' : number,
    }
  >,
  'updateTrade' : ActorMethod<[Trade], undefined>,
  'validateBracketGroups' : ActorMethod<[Array<BracketGroup>, string], boolean>,
  'validateBracketOrderRules' : ActorMethod<
    [BracketOrderOutcome, BracketOrder],
    { 'valid' : null } |
      { 'invalid_take_profit_order' : null } |
      { 'invalid_event_combination' : null } |
      { 'invalid_stop_loss_adjustment' : null }
  >,
  'validateOutcomeSequence' : ActorMethod<[Array<FilledBracketGroup>], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];