/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ModelCondition = IDL.Record({
  'id' : IDL.Text,
  'isChecked' : IDL.Bool,
  'zone' : IDL.Text,
  'description' : IDL.Text,
});
export const PropertyType = IDL.Variant({
  'text' : IDL.Null,
  'select' : IDL.Null,
  'toggle' : IDL.Null,
  'number' : IDL.Null,
});
export const CustomProperty = IDL.Record({
  'id' : IDL.Text,
  'type' : PropertyType,
  'propertyLabel' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'default_value' : IDL.Text,
});
export const CustomToolDefinition = IDL.Record({
  'id' : IDL.Text,
  'updated_at' : IDL.Int,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'properties' : IDL.Vec(CustomProperty),
  'created_at' : IDL.Int,
});
export const ToolConfig = IDL.Record({
  'id' : IDL.Text,
  'type' : IDL.Text,
  'zone' : IDL.Text,
  'properties' : IDL.Text,
  'actions' : IDL.Vec(IDL.Text),
  'interactions' : IDL.Vec(IDL.Text),
  'position' : IDL.Nat,
});
export const Model = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'framework' : IDL.Vec(ToolConfig),
  'description' : IDL.Text,
  'created_at' : IDL.Int,
  'narrative' : IDL.Vec(ToolConfig),
  'execution' : IDL.Vec(ToolConfig),
});
export const ClosureType = IDL.Variant({
  'take_profit' : IDL.Null,
  'manual_close' : IDL.Null,
  'stop_loss' : IDL.Null,
  'break_even' : IDL.Null,
});
export const FilledBracketGroup = IDL.Record({
  'manual_close_price' : IDL.Opt(IDL.Float64),
  'break_even_applied' : IDL.Bool,
  'closure_price' : IDL.Float64,
  'size' : IDL.Float64,
  'break_even_price' : IDL.Opt(IDL.Float64),
  'bracket_id' : IDL.Text,
  'manual_close_applied' : IDL.Bool,
  'closure_type' : ClosureType,
});
export const BracketOrderOutcome = IDL.Record({
  'rr' : IDL.Float64,
  'final_pl_pct' : IDL.Float64,
  'final_pl_usd' : IDL.Float64,
  'filled_bracket_groups' : IDL.Vec(FilledBracketGroup),
});
export const CalculationMethod = IDL.Variant({
  'tick' : IDL.Null,
  'point' : IDL.Null,
});
export const PositionSizer = IDL.Record({
  'contract_lot_unit' : IDL.Text,
  'allow_fractional_size' : IDL.Bool,
  'asset_type' : IDL.Text,
  'account_capital' : IDL.Float64,
  'value_per_point' : IDL.Float64,
  'primary_stop_loss' : IDL.Float64,
  'risk_percentage' : IDL.Float64,
  'entry_price' : IDL.Float64,
});
export const BracketGroup = IDL.Record({
  'size' : IDL.Float64,
  'take_profit_price' : IDL.Float64,
  'sl_modified_by_user' : IDL.Bool,
  'bracket_id' : IDL.Text,
  'stop_loss_price' : IDL.Float64,
});
export const BracketOrder = IDL.Record({
  'bracket_groups' : IDL.Vec(BracketGroup),
  'primary_stop_loss' : IDL.Float64,
  'calculation_method' : IDL.Text,
  'position_sizer' : PositionSizer,
  'position_size' : IDL.Float64,
  'entry_price' : IDL.Float64,
  'value_per_unit' : IDL.Float64,
});
export const Trade = IDL.Record({
  'id' : IDL.Text,
  'direction' : IDL.Text,
  'asset' : IDL.Text,
  'owner' : IDL.Principal,
  'model_conditions' : IDL.Vec(ModelCondition),
  'created_at' : IDL.Int,
  'bracket_order_outcome' : BracketOrderOutcome,
  'calculation_method' : CalculationMethod,
  'is_completed' : IDL.Bool,
  'position_sizer' : PositionSizer,
  'notes' : IDL.Text,
  'adherence_score' : IDL.Float64,
  'emotions' : IDL.Vec(IDL.Text),
  'model_id' : IDL.Text,
  'bracket_order' : BracketOrder,
  'value_per_unit' : IDL.Float64,
  'images' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateAdherenceScore' : IDL.Func(
      [IDL.Vec(ModelCondition)],
      [IDL.Float64],
      ['query'],
    ),
  'createCustomTool' : IDL.Func([CustomToolDefinition], [IDL.Text], []),
  'createModel' : IDL.Func([Model], [], []),
  'createTrade' : IDL.Func([Trade], [], []),
  'deleteCustomTool' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteModel' : IDL.Func([IDL.Text], [], []),
  'deleteTrade' : IDL.Func([IDL.Text], [], []),
  'duplicateCustomTool' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAdherenceAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'avg_adherence' : IDL.Float64,
          'total_trades' : IDL.Nat,
          'win_rate_high_adherence' : IDL.Float64,
          'win_rate_low_adherence' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getAllCustomTools' : IDL.Func(
      [],
      [IDL.Vec(CustomToolDefinition)],
      ['query'],
    ),
  'getAllModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
  'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
  'getCustomTool' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomToolDefinition)],
      ['query'],
    ),
  'getCustomToolCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getModel' : IDL.Func([IDL.Text], [IDL.Opt(Model)], ['query']),
  'getModelConditions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ModelCondition)],
      ['query'],
    ),
  'getTotalAllocation' : IDL.Func(
      [IDL.Vec(BracketGroup)],
      [IDL.Float64],
      ['query'],
    ),
  'getTrade' : IDL.Func([IDL.Text], [IDL.Opt(Trade)], ['query']),
  'getTradesByAdherenceRange' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(Trade)],
      ['query'],
    ),
  'getTradesByAsset' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
  'getTradesByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Trade)],
      ['query'],
    ),
  'getTradesByModel' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mapTradeConditionsToModel' : IDL.Func(
      [IDL.Vec(ModelCondition), IDL.Vec(ModelCondition)],
      [IDL.Vec(ModelCondition)],
      ['query'],
    ),
  'saveBracketOrderOutcome' : IDL.Func(
      [IDL.Text, BracketOrderOutcome],
      [
        IDL.Record({
          'updatedTrade' : Trade,
          'updatedAnalytics' : IDL.Record({
            'totalTrades' : IDL.Float64,
            'avgPL' : IDL.Float64,
            'avgRR' : IDL.Float64,
            'totalPL' : IDL.Float64,
            'totalRR' : IDL.Float64,
            'totalWins' : IDL.Float64,
            'bracketOrderValidation' : IDL.Variant({
              'valid' : IDL.Null,
              'invalid_take_profit_order' : IDL.Null,
              'invalid_event_combination' : IDL.Null,
              'invalid_stop_loss_adjustment' : IDL.Null,
            }),
            'winRate' : IDL.Float64,
          }),
        }),
      ],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomTool' : IDL.Func([CustomToolDefinition], [IDL.Text], []),
  'updateModel' : IDL.Func([Model], [], []),
  'updateModelAnalytics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalTrades' : IDL.Float64,
          'avgPL' : IDL.Float64,
          'avgRR' : IDL.Float64,
          'totalPL' : IDL.Float64,
          'totalRR' : IDL.Float64,
          'totalWins' : IDL.Float64,
          'bracketOrderValidation' : IDL.Variant({
            'valid' : IDL.Null,
            'invalid_take_profit_order' : IDL.Null,
            'invalid_event_combination' : IDL.Null,
            'invalid_stop_loss_adjustment' : IDL.Null,
          }),
          'winRate' : IDL.Float64,
        }),
      ],
      [],
    ),
  'updateTrade' : IDL.Func([Trade], [], []),
  'validateBracketGroups' : IDL.Func(
      [IDL.Vec(BracketGroup), IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'validateBracketOrderRules' : IDL.Func(
      [BracketOrderOutcome, BracketOrder],
      [
        IDL.Variant({
          'valid' : IDL.Null,
          'invalid_take_profit_order' : IDL.Null,
          'invalid_event_combination' : IDL.Null,
          'invalid_stop_loss_adjustment' : IDL.Null,
        }),
      ],
      ['query'],
    ),
  'validateOutcomeSequence' : IDL.Func(
      [IDL.Vec(FilledBracketGroup)],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ModelCondition = IDL.Record({
    'id' : IDL.Text,
    'isChecked' : IDL.Bool,
    'zone' : IDL.Text,
    'description' : IDL.Text,
  });
  const PropertyType = IDL.Variant({
    'text' : IDL.Null,
    'select' : IDL.Null,
    'toggle' : IDL.Null,
    'number' : IDL.Null,
  });
  const CustomProperty = IDL.Record({
    'id' : IDL.Text,
    'type' : PropertyType,
    'propertyLabel' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'default_value' : IDL.Text,
  });
  const CustomToolDefinition = IDL.Record({
    'id' : IDL.Text,
    'updated_at' : IDL.Int,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'properties' : IDL.Vec(CustomProperty),
    'created_at' : IDL.Int,
  });
  const ToolConfig = IDL.Record({
    'id' : IDL.Text,
    'type' : IDL.Text,
    'zone' : IDL.Text,
    'properties' : IDL.Text,
    'actions' : IDL.Vec(IDL.Text),
    'interactions' : IDL.Vec(IDL.Text),
    'position' : IDL.Nat,
  });
  const Model = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'framework' : IDL.Vec(ToolConfig),
    'description' : IDL.Text,
    'created_at' : IDL.Int,
    'narrative' : IDL.Vec(ToolConfig),
    'execution' : IDL.Vec(ToolConfig),
  });
  const ClosureType = IDL.Variant({
    'take_profit' : IDL.Null,
    'manual_close' : IDL.Null,
    'stop_loss' : IDL.Null,
    'break_even' : IDL.Null,
  });
  const FilledBracketGroup = IDL.Record({
    'manual_close_price' : IDL.Opt(IDL.Float64),
    'break_even_applied' : IDL.Bool,
    'closure_price' : IDL.Float64,
    'size' : IDL.Float64,
    'break_even_price' : IDL.Opt(IDL.Float64),
    'bracket_id' : IDL.Text,
    'manual_close_applied' : IDL.Bool,
    'closure_type' : ClosureType,
  });
  const BracketOrderOutcome = IDL.Record({
    'rr' : IDL.Float64,
    'final_pl_pct' : IDL.Float64,
    'final_pl_usd' : IDL.Float64,
    'filled_bracket_groups' : IDL.Vec(FilledBracketGroup),
  });
  const CalculationMethod = IDL.Variant({
    'tick' : IDL.Null,
    'point' : IDL.Null,
  });
  const PositionSizer = IDL.Record({
    'contract_lot_unit' : IDL.Text,
    'allow_fractional_size' : IDL.Bool,
    'asset_type' : IDL.Text,
    'account_capital' : IDL.Float64,
    'value_per_point' : IDL.Float64,
    'primary_stop_loss' : IDL.Float64,
    'risk_percentage' : IDL.Float64,
    'entry_price' : IDL.Float64,
  });
  const BracketGroup = IDL.Record({
    'size' : IDL.Float64,
    'take_profit_price' : IDL.Float64,
    'sl_modified_by_user' : IDL.Bool,
    'bracket_id' : IDL.Text,
    'stop_loss_price' : IDL.Float64,
  });
  const BracketOrder = IDL.Record({
    'bracket_groups' : IDL.Vec(BracketGroup),
    'primary_stop_loss' : IDL.Float64,
    'calculation_method' : IDL.Text,
    'position_sizer' : PositionSizer,
    'position_size' : IDL.Float64,
    'entry_price' : IDL.Float64,
    'value_per_unit' : IDL.Float64,
  });
  const Trade = IDL.Record({
    'id' : IDL.Text,
    'direction' : IDL.Text,
    'asset' : IDL.Text,
    'owner' : IDL.Principal,
    'model_conditions' : IDL.Vec(ModelCondition),
    'created_at' : IDL.Int,
    'bracket_order_outcome' : BracketOrderOutcome,
    'calculation_method' : CalculationMethod,
    'is_completed' : IDL.Bool,
    'position_sizer' : PositionSizer,
    'notes' : IDL.Text,
    'adherence_score' : IDL.Float64,
    'emotions' : IDL.Vec(IDL.Text),
    'model_id' : IDL.Text,
    'bracket_order' : BracketOrder,
    'value_per_unit' : IDL.Float64,
    'images' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateAdherenceScore' : IDL.Func(
        [IDL.Vec(ModelCondition)],
        [IDL.Float64],
        ['query'],
      ),
    'createCustomTool' : IDL.Func([CustomToolDefinition], [IDL.Text], []),
    'createModel' : IDL.Func([Model], [], []),
    'createTrade' : IDL.Func([Trade], [], []),
    'deleteCustomTool' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteModel' : IDL.Func([IDL.Text], [], []),
    'deleteTrade' : IDL.Func([IDL.Text], [], []),
    'duplicateCustomTool' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAdherenceAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'avg_adherence' : IDL.Float64,
            'total_trades' : IDL.Nat,
            'win_rate_high_adherence' : IDL.Float64,
            'win_rate_low_adherence' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getAllCustomTools' : IDL.Func(
        [],
        [IDL.Vec(CustomToolDefinition)],
        ['query'],
      ),
    'getAllModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
    'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
    'getCustomTool' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomToolDefinition)],
        ['query'],
      ),
    'getCustomToolCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getModel' : IDL.Func([IDL.Text], [IDL.Opt(Model)], ['query']),
    'getModelConditions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ModelCondition)],
        ['query'],
      ),
    'getTotalAllocation' : IDL.Func(
        [IDL.Vec(BracketGroup)],
        [IDL.Float64],
        ['query'],
      ),
    'getTrade' : IDL.Func([IDL.Text], [IDL.Opt(Trade)], ['query']),
    'getTradesByAdherenceRange' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(Trade)],
        ['query'],
      ),
    'getTradesByAsset' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
    'getTradesByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Trade)],
        ['query'],
      ),
    'getTradesByModel' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mapTradeConditionsToModel' : IDL.Func(
        [IDL.Vec(ModelCondition), IDL.Vec(ModelCondition)],
        [IDL.Vec(ModelCondition)],
        ['query'],
      ),
    'saveBracketOrderOutcome' : IDL.Func(
        [IDL.Text, BracketOrderOutcome],
        [
          IDL.Record({
            'updatedTrade' : Trade,
            'updatedAnalytics' : IDL.Record({
              'totalTrades' : IDL.Float64,
              'avgPL' : IDL.Float64,
              'avgRR' : IDL.Float64,
              'totalPL' : IDL.Float64,
              'totalRR' : IDL.Float64,
              'totalWins' : IDL.Float64,
              'bracketOrderValidation' : IDL.Variant({
                'valid' : IDL.Null,
                'invalid_take_profit_order' : IDL.Null,
                'invalid_event_combination' : IDL.Null,
                'invalid_stop_loss_adjustment' : IDL.Null,
              }),
              'winRate' : IDL.Float64,
            }),
          }),
        ],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomTool' : IDL.Func([CustomToolDefinition], [IDL.Text], []),
    'updateModel' : IDL.Func([Model], [], []),
    'updateModelAnalytics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalTrades' : IDL.Float64,
            'avgPL' : IDL.Float64,
            'avgRR' : IDL.Float64,
            'totalPL' : IDL.Float64,
            'totalRR' : IDL.Float64,
            'totalWins' : IDL.Float64,
            'bracketOrderValidation' : IDL.Variant({
              'valid' : IDL.Null,
              'invalid_take_profit_order' : IDL.Null,
              'invalid_event_combination' : IDL.Null,
              'invalid_stop_loss_adjustment' : IDL.Null,
            }),
            'winRate' : IDL.Float64,
          }),
        ],
        [],
      ),
    'updateTrade' : IDL.Func([Trade], [], []),
    'validateBracketGroups' : IDL.Func(
        [IDL.Vec(BracketGroup), IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'validateBracketOrderRules' : IDL.Func(
        [BracketOrderOutcome, BracketOrder],
        [
          IDL.Variant({
            'valid' : IDL.Null,
            'invalid_take_profit_order' : IDL.Null,
            'invalid_event_combination' : IDL.Null,
            'invalid_stop_loss_adjustment' : IDL.Null,
          }),
        ],
        ['query'],
      ),
    'validateOutcomeSequence' : IDL.Func(
        [IDL.Vec(FilledBracketGroup)],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };