/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BracketOrder {
    bracket_groups: Array<BracketGroup>;
    primary_stop_loss: number;
    calculation_method: string;
    position_sizer: PositionSizer;
    position_size: number;
    entry_price: number;
    value_per_unit: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Trade {
    id: string;
    direction: string;
    asset: string;
    owner: Principal;
    model_conditions: Array<ModelCondition>;
    created_at: bigint;
    bracket_order_outcome: BracketOrderOutcome;
    calculation_method: CalculationMethod;
    is_completed: boolean;
    position_sizer: PositionSizer;
    notes: string;
    adherence_score: number;
    emotions: Array<string>;
    model_id: string;
    bracket_order: BracketOrder;
    value_per_unit: number;
    images: Array<string>;
}
export interface CustomToolDefinition {
    id: string;
    updated_at: bigint;
    owner: Principal;
    name: string;
    properties: Array<CustomProperty>;
    created_at: bigint;
}
export interface BracketGroup {
    size: number;
    take_profit_price: number;
    sl_modified_by_user: boolean;
    bracket_id: string;
    stop_loss_price: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ModelCondition {
    id: string;
    isChecked: boolean;
    zone: string;
    description: string;
}
export interface BracketOrderOutcome {
    rr: number;
    final_pl_pct: number;
    final_pl_usd: number;
    filled_bracket_groups: Array<FilledBracketGroup>;
}
export interface ToolConfig {
    id: string;
    type: string;
    zone: string;
    properties: string;
    actions: Array<string>;
    interactions: Array<string>;
    position: bigint;
}
export interface PositionSizer {
    contract_lot_unit: string;
    allow_fractional_size: boolean;
    asset_type: string;
    account_capital: number;
    value_per_point: number;
    primary_stop_loss: number;
    risk_percentage: number;
    entry_price: number;
}
export interface FilledBracketGroup {
    manual_close_price?: number;
    break_even_applied: boolean;
    closure_price: number;
    size: number;
    break_even_price?: number;
    bracket_id: string;
    manual_close_applied: boolean;
    closure_type: ClosureType;
}
export interface Model {
    id: string;
    owner: Principal;
    name: string;
    framework: Array<ToolConfig>;
    description: string;
    created_at: bigint;
    narrative: Array<ToolConfig>;
    execution: Array<ToolConfig>;
}
export interface CustomProperty {
    id: string;
    type: PropertyType;
    propertyLabel: string;
    options: Array<string>;
    default_value: string;
}
export interface UserProfile {
    name: string;
}
export enum CalculationMethod {
    tick = "tick",
    point = "point"
}
export enum ClosureType {
    take_profit = "take_profit",
    manual_close = "manual_close",
    stop_loss = "stop_loss",
    break_even = "break_even"
}
export enum PropertyType {
    text = "text",
    select = "select",
    toggle = "toggle",
    number_ = "number"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment {
    valid = "valid",
    invalid_take_profit_order = "invalid_take_profit_order",
    invalid_event_combination = "invalid_event_combination",
    invalid_stop_loss_adjustment = "invalid_stop_loss_adjustment"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateAdherenceScore(conditions: Array<ModelCondition>): Promise<number>;
    createCustomTool(tool: CustomToolDefinition): Promise<string>;
    createModel(model: Model): Promise<void>;
    createTrade(trade: Trade): Promise<void>;
    deleteCustomTool(id: string): Promise<string>;
    deleteModel(id: string): Promise<void>;
    deleteTrade(id: string): Promise<void>;
    duplicateCustomTool(tool_id: string, new_name: string): Promise<string>;
    getAdherenceAnalytics(): Promise<{
        avg_adherence: number;
        total_trades: bigint;
        win_rate_high_adherence: number;
        win_rate_low_adherence: number;
    }>;
    getAllCustomTools(): Promise<Array<CustomToolDefinition>>;
    getAllModels(): Promise<Array<Model>>;
    getAllTrades(): Promise<Array<Trade>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentTime(): Promise<bigint>;
    getCustomTool(id: string): Promise<CustomToolDefinition | null>;
    getCustomToolCount(): Promise<bigint>;
    getModel(id: string): Promise<Model | null>;
    getModelConditions(model_id: string): Promise<Array<ModelCondition>>;
    getTotalAllocation(bracket_groups: Array<BracketGroup>): Promise<number>;
    getTrade(id: string): Promise<Trade | null>;
    getTradesByAdherenceRange(min_score: number, max_score: number): Promise<Array<Trade>>;
    getTradesByAsset(asset: string): Promise<Array<Trade>>;
    getTradesByDateRange(start: bigint, end: bigint): Promise<Array<Trade>>;
    getTradesByModel(model_id: string): Promise<Array<Trade>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    mapTradeConditionsToModel(trade_conditions: Array<ModelCondition>, model_conditions: Array<ModelCondition>): Promise<Array<ModelCondition>>;
    saveBracketOrderOutcome(trade_id: string, outcome_data: BracketOrderOutcome): Promise<{
        updatedTrade: Trade;
        updatedAnalytics: {
            totalTrades: number;
            avgPL: number;
            avgRR: number;
            totalPL: number;
            totalRR: number;
            totalWins: number;
            bracketOrderValidation: Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment;
            winRate: number;
        };
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCustomTool(tool: CustomToolDefinition): Promise<string>;
    updateModel(model: Model): Promise<void>;
    updateModelAnalytics(model_id: string, caller_principal: Principal): Promise<{
        totalTrades: number;
        avgPL: number;
        avgRR: number;
        totalPL: number;
        totalRR: number;
        totalWins: number;
        bracketOrderValidation: Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment;
        winRate: number;
    }>;
    updateTrade(trade: Trade): Promise<void>;
    validateBracketGroups(bracket_groups: Array<BracketGroup>, direction: string): Promise<boolean>;
    validateBracketOrderRules(outcome_data: BracketOrderOutcome, original_bracket_order: BracketOrder): Promise<Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment>;
    validateOutcomeSequence(filled_bracket_groups: Array<FilledBracketGroup>): Promise<boolean>;
}
import type { BracketOrder as _BracketOrder, BracketOrderOutcome as _BracketOrderOutcome, CalculationMethod as _CalculationMethod, ClosureType as _ClosureType, CustomProperty as _CustomProperty, CustomToolDefinition as _CustomToolDefinition, FilledBracketGroup as _FilledBracketGroup, Model as _Model, ModelCondition as _ModelCondition, PositionSizer as _PositionSizer, PropertyType as _PropertyType, Trade as _Trade, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateAdherenceScore(arg0: Array<ModelCondition>): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateAdherenceScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateAdherenceScore(arg0);
            return result;
        }
    }
    async createCustomTool(arg0: CustomToolDefinition): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomTool(to_candid_CustomToolDefinition_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomTool(to_candid_CustomToolDefinition_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createModel(arg0: Model): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createModel(arg0);
            return result;
        }
    }
    async createTrade(arg0: Trade): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrade(to_candid_Trade_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrade(to_candid_Trade_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCustomTool(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomTool(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomTool(arg0);
            return result;
        }
    }
    async deleteModel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteModel(arg0);
            return result;
        }
    }
    async deleteTrade(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async duplicateCustomTool(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateCustomTool(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateCustomTool(arg0, arg1);
            return result;
        }
    }
    async getAdherenceAnalytics(): Promise<{
        avg_adherence: number;
        total_trades: bigint;
        win_rate_high_adherence: number;
        win_rate_low_adherence: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdherenceAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdherenceAnalytics();
            return result;
        }
    }
    async getAllCustomTools(): Promise<Array<CustomToolDefinition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomTools();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomTools();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllModels(): Promise<Array<Model>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllModels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllModels();
            return result;
        }
    }
    async getAllTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTime();
            return result;
        }
    }
    async getCustomTool(arg0: string): Promise<CustomToolDefinition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomTool(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomTool(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomToolCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomToolCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomToolCount();
            return result;
        }
    }
    async getModel(arg0: string): Promise<Model | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModel(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModel(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModelConditions(arg0: string): Promise<Array<ModelCondition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModelConditions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModelConditions(arg0);
            return result;
        }
    }
    async getTotalAllocation(arg0: Array<BracketGroup>): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalAllocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalAllocation(arg0);
            return result;
        }
    }
    async getTrade(arg0: string): Promise<Trade | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrade(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrade(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByAdherenceRange(arg0: number, arg1: number): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByAdherenceRange(arg0, arg1);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByAdherenceRange(arg0, arg1);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByAsset(arg0: string): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByAsset(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByAsset(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByDateRange(arg0, arg1);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByDateRange(arg0, arg1);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByModel(arg0: string): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByModel(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByModel(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async mapTradeConditionsToModel(arg0: Array<ModelCondition>, arg1: Array<ModelCondition>): Promise<Array<ModelCondition>> {
        if (this.processError) {
            try {
                const result = await this.actor.mapTradeConditionsToModel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mapTradeConditionsToModel(arg0, arg1);
            return result;
        }
    }
    async saveBracketOrderOutcome(arg0: string, arg1: BracketOrderOutcome): Promise<{
        updatedTrade: Trade;
        updatedAnalytics: {
            totalTrades: number;
            avgPL: number;
            avgRR: number;
            totalPL: number;
            totalRR: number;
            totalWins: number;
            bracketOrderValidation: Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment;
            winRate: number;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBracketOrderOutcome(arg0, to_candid_BracketOrderOutcome_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_record_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBracketOrderOutcome(arg0, to_candid_BracketOrderOutcome_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_record_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCustomTool(arg0: CustomToolDefinition): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomTool(to_candid_CustomToolDefinition_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomTool(to_candid_CustomToolDefinition_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateModel(arg0: Model): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateModel(arg0);
            return result;
        }
    }
    async updateModelAnalytics(arg0: string, arg1: Principal): Promise<{
        totalTrades: number;
        avgPL: number;
        avgRR: number;
        totalPL: number;
        totalRR: number;
        totalWins: number;
        bracketOrderValidation: Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment;
        winRate: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateModelAnalytics(arg0, arg1);
                return from_candid_record_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateModelAnalytics(arg0, arg1);
            return from_candid_record_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTrade(arg0: Trade): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(to_candid_Trade_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(to_candid_Trade_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateBracketGroups(arg0: Array<BracketGroup>, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateBracketGroups(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateBracketGroups(arg0, arg1);
            return result;
        }
    }
    async validateBracketOrderRules(arg0: BracketOrderOutcome, arg1: BracketOrder): Promise<Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment> {
        if (this.processError) {
            try {
                const result = await this.actor.validateBracketOrderRules(to_candid_BracketOrderOutcome_n19(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateBracketOrderRules(to_candid_BracketOrderOutcome_n19(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateOutcomeSequence(arg0: Array<FilledBracketGroup>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateOutcomeSequence(to_candid_vec_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateOutcomeSequence(to_candid_vec_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BracketOrderOutcome_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BracketOrderOutcome): BracketOrderOutcome {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_CalculationMethod_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalculationMethod): CalculationMethod {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ClosureType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClosureType): ClosureType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_CustomProperty_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomProperty): CustomProperty {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_CustomToolDefinition_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomToolDefinition): CustomToolDefinition {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_FilledBracketGroup_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FilledBracketGroup): FilledBracketGroup {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomToolDefinition]): CustomToolDefinition | null {
    return value.length === 0 ? null : from_candid_CustomToolDefinition_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Model]): Model | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trade]): Trade | null {
    return value.length === 0 ? null : from_candid_Trade_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    updated_at: bigint;
    owner: Principal;
    name: string;
    properties: Array<_CustomProperty>;
    created_at: bigint;
}): {
    id: string;
    updated_at: bigint;
    owner: Principal;
    name: string;
    properties: Array<CustomProperty>;
    created_at: bigint;
} {
    return {
        id: value.id,
        updated_at: value.updated_at,
        owner: value.owner,
        name: value.name,
        properties: from_candid_vec_n31(_uploadFile, _downloadFile, value.properties),
        created_at: value.created_at
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    type: _PropertyType;
    propertyLabel: string;
    options: Array<string>;
    default_value: string;
}): {
    id: string;
    type: PropertyType;
    propertyLabel: string;
    options: Array<string>;
    default_value: string;
} {
    return {
        id: value.id,
        type: from_candid_PropertyType_n34(_uploadFile, _downloadFile, value.type),
        propertyLabel: value.propertyLabel,
        options: value.options,
        default_value: value.default_value
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    direction: string;
    asset: string;
    owner: Principal;
    model_conditions: Array<_ModelCondition>;
    created_at: bigint;
    bracket_order_outcome: _BracketOrderOutcome;
    calculation_method: _CalculationMethod;
    is_completed: boolean;
    position_sizer: _PositionSizer;
    notes: string;
    adherence_score: number;
    emotions: Array<string>;
    model_id: string;
    bracket_order: _BracketOrder;
    value_per_unit: number;
    images: Array<string>;
}): {
    id: string;
    direction: string;
    asset: string;
    owner: Principal;
    model_conditions: Array<ModelCondition>;
    created_at: bigint;
    bracket_order_outcome: BracketOrderOutcome;
    calculation_method: CalculationMethod;
    is_completed: boolean;
    position_sizer: PositionSizer;
    notes: string;
    adherence_score: number;
    emotions: Array<string>;
    model_id: string;
    bracket_order: BracketOrder;
    value_per_unit: number;
    images: Array<string>;
} {
    return {
        id: value.id,
        direction: value.direction,
        asset: value.asset,
        owner: value.owner,
        model_conditions: value.model_conditions,
        created_at: value.created_at,
        bracket_order_outcome: from_candid_BracketOrderOutcome_n39(_uploadFile, _downloadFile, value.bracket_order_outcome),
        calculation_method: from_candid_CalculationMethod_n47(_uploadFile, _downloadFile, value.calculation_method),
        is_completed: value.is_completed,
        position_sizer: value.position_sizer,
        notes: value.notes,
        adherence_score: value.adherence_score,
        emotions: value.emotions,
        model_id: value.model_id,
        bracket_order: value.bracket_order,
        value_per_unit: value.value_per_unit,
        images: value.images
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rr: number;
    final_pl_pct: number;
    final_pl_usd: number;
    filled_bracket_groups: Array<_FilledBracketGroup>;
}): {
    rr: number;
    final_pl_pct: number;
    final_pl_usd: number;
    filled_bracket_groups: Array<FilledBracketGroup>;
} {
    return {
        rr: value.rr,
        final_pl_pct: value.final_pl_pct,
        final_pl_usd: value.final_pl_usd,
        filled_bracket_groups: from_candid_vec_n41(_uploadFile, _downloadFile, value.filled_bracket_groups)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manual_close_price: [] | [number];
    break_even_applied: boolean;
    closure_price: number;
    size: number;
    break_even_price: [] | [number];
    bracket_id: string;
    manual_close_applied: boolean;
    closure_type: _ClosureType;
}): {
    manual_close_price?: number;
    break_even_applied: boolean;
    closure_price: number;
    size: number;
    break_even_price?: number;
    bracket_id: string;
    manual_close_applied: boolean;
    closure_type: ClosureType;
} {
    return {
        manual_close_price: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.manual_close_price)),
        break_even_applied: value.break_even_applied,
        closure_price: value.closure_price,
        size: value.size,
        break_even_price: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.break_even_price)),
        bracket_id: value.bracket_id,
        manual_close_applied: value.manual_close_applied,
        closure_type: from_candid_ClosureType_n45(_uploadFile, _downloadFile, value.closure_type)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    updatedTrade: _Trade;
    updatedAnalytics: {
        totalTrades: number;
        avgPL: number;
        avgRR: number;
        totalPL: number;
        totalRR: number;
        totalWins: number;
        bracketOrderValidation: {
            valid: null;
        } | {
            invalid_take_profit_order: null;
        } | {
            invalid_event_combination: null;
        } | {
            invalid_stop_loss_adjustment: null;
        };
        winRate: number;
    };
}): {
    updatedTrade: Trade;
    updatedAnalytics: {
        totalTrades: number;
        avgPL: number;
        avgRR: number;
        totalPL: number;
        totalRR: number;
        totalWins: number;
        bracketOrderValidation: Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment;
        winRate: number;
    };
} {
    return {
        updatedTrade: from_candid_Trade_n37(_uploadFile, _downloadFile, value.updatedTrade),
        updatedAnalytics: from_candid_record_n56(_uploadFile, _downloadFile, value.updatedAnalytics)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalTrades: number;
    avgPL: number;
    avgRR: number;
    totalPL: number;
    totalRR: number;
    totalWins: number;
    bracketOrderValidation: {
        valid: null;
    } | {
        invalid_take_profit_order: null;
    } | {
        invalid_event_combination: null;
    } | {
        invalid_stop_loss_adjustment: null;
    };
    winRate: number;
}): {
    totalTrades: number;
    avgPL: number;
    avgRR: number;
    totalPL: number;
    totalRR: number;
    totalWins: number;
    bracketOrderValidation: Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment;
    winRate: number;
} {
    return {
        totalTrades: value.totalTrades,
        avgPL: value.avgPL,
        avgRR: value.avgRR,
        totalPL: value.totalPL,
        totalRR: value.totalRR,
        totalWins: value.totalWins,
        bracketOrderValidation: from_candid_variant_n57(_uploadFile, _downloadFile, value.bracketOrderValidation),
        winRate: value.winRate
    };
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    select: null;
} | {
    toggle: null;
} | {
    number: null;
}): PropertyType {
    return "text" in value ? PropertyType.text : "select" in value ? PropertyType.select : "toggle" in value ? PropertyType.toggle : "number" in value ? PropertyType.number : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    take_profit: null;
} | {
    manual_close: null;
} | {
    stop_loss: null;
} | {
    break_even: null;
}): ClosureType {
    return "take_profit" in value ? ClosureType.take_profit : "manual_close" in value ? ClosureType.manual_close : "stop_loss" in value ? ClosureType.stop_loss : "break_even" in value ? ClosureType.break_even : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tick: null;
} | {
    point: null;
}): CalculationMethod {
    return "tick" in value ? CalculationMethod.tick : "point" in value ? CalculationMethod.point : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    valid: null;
} | {
    invalid_take_profit_order: null;
} | {
    invalid_event_combination: null;
} | {
    invalid_stop_loss_adjustment: null;
}): Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment {
    return "valid" in value ? Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment.valid : "invalid_take_profit_order" in value ? Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment.invalid_take_profit_order : "invalid_event_combination" in value ? Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment.invalid_event_combination : "invalid_stop_loss_adjustment" in value ? Variant_valid_invalid_take_profit_order_invalid_event_combination_invalid_stop_loss_adjustment.invalid_stop_loss_adjustment : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomToolDefinition>): Array<CustomToolDefinition> {
    return value.map((x)=>from_candid_CustomToolDefinition_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomProperty>): Array<CustomProperty> {
    return value.map((x)=>from_candid_CustomProperty_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FilledBracketGroup>): Array<FilledBracketGroup> {
    return value.map((x)=>from_candid_FilledBracketGroup_n42(_uploadFile, _downloadFile, x));
}
function to_candid_BracketOrderOutcome_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BracketOrderOutcome): _BracketOrderOutcome {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CalculationMethod_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalculationMethod): _CalculationMethod {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_ClosureType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClosureType): _ClosureType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_CustomProperty_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomProperty): _CustomProperty {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_CustomToolDefinition_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomToolDefinition): _CustomToolDefinition {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_FilledBracketGroup_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilledBracketGroup): _FilledBracketGroup {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    updated_at: bigint;
    owner: Principal;
    name: string;
    properties: Array<CustomProperty>;
    created_at: bigint;
}): {
    id: string;
    updated_at: bigint;
    owner: Principal;
    name: string;
    properties: Array<_CustomProperty>;
    created_at: bigint;
} {
    return {
        id: value.id,
        updated_at: value.updated_at,
        owner: value.owner,
        name: value.name,
        properties: to_candid_vec_n12(_uploadFile, _downloadFile, value.properties),
        created_at: value.created_at
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    type: PropertyType;
    propertyLabel: string;
    options: Array<string>;
    default_value: string;
}): {
    id: string;
    type: _PropertyType;
    propertyLabel: string;
    options: Array<string>;
    default_value: string;
} {
    return {
        id: value.id,
        type: to_candid_PropertyType_n15(_uploadFile, _downloadFile, value.type),
        propertyLabel: value.propertyLabel,
        options: value.options,
        default_value: value.default_value
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    direction: string;
    asset: string;
    owner: Principal;
    model_conditions: Array<ModelCondition>;
    created_at: bigint;
    bracket_order_outcome: BracketOrderOutcome;
    calculation_method: CalculationMethod;
    is_completed: boolean;
    position_sizer: PositionSizer;
    notes: string;
    adherence_score: number;
    emotions: Array<string>;
    model_id: string;
    bracket_order: BracketOrder;
    value_per_unit: number;
    images: Array<string>;
}): {
    id: string;
    direction: string;
    asset: string;
    owner: Principal;
    model_conditions: Array<_ModelCondition>;
    created_at: bigint;
    bracket_order_outcome: _BracketOrderOutcome;
    calculation_method: _CalculationMethod;
    is_completed: boolean;
    position_sizer: _PositionSizer;
    notes: string;
    adherence_score: number;
    emotions: Array<string>;
    model_id: string;
    bracket_order: _BracketOrder;
    value_per_unit: number;
    images: Array<string>;
} {
    return {
        id: value.id,
        direction: value.direction,
        asset: value.asset,
        owner: value.owner,
        model_conditions: value.model_conditions,
        created_at: value.created_at,
        bracket_order_outcome: to_candid_BracketOrderOutcome_n19(_uploadFile, _downloadFile, value.bracket_order_outcome),
        calculation_method: to_candid_CalculationMethod_n26(_uploadFile, _downloadFile, value.calculation_method),
        is_completed: value.is_completed,
        position_sizer: value.position_sizer,
        notes: value.notes,
        adherence_score: value.adherence_score,
        emotions: value.emotions,
        model_id: value.model_id,
        bracket_order: value.bracket_order,
        value_per_unit: value.value_per_unit,
        images: value.images
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rr: number;
    final_pl_pct: number;
    final_pl_usd: number;
    filled_bracket_groups: Array<FilledBracketGroup>;
}): {
    rr: number;
    final_pl_pct: number;
    final_pl_usd: number;
    filled_bracket_groups: Array<_FilledBracketGroup>;
} {
    return {
        rr: value.rr,
        final_pl_pct: value.final_pl_pct,
        final_pl_usd: value.final_pl_usd,
        filled_bracket_groups: to_candid_vec_n21(_uploadFile, _downloadFile, value.filled_bracket_groups)
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manual_close_price?: number;
    break_even_applied: boolean;
    closure_price: number;
    size: number;
    break_even_price?: number;
    bracket_id: string;
    manual_close_applied: boolean;
    closure_type: ClosureType;
}): {
    manual_close_price: [] | [number];
    break_even_applied: boolean;
    closure_price: number;
    size: number;
    break_even_price: [] | [number];
    bracket_id: string;
    manual_close_applied: boolean;
    closure_type: _ClosureType;
} {
    return {
        manual_close_price: value.manual_close_price ? candid_some(value.manual_close_price) : candid_none(),
        break_even_applied: value.break_even_applied,
        closure_price: value.closure_price,
        size: value.size,
        break_even_price: value.break_even_price ? candid_some(value.break_even_price) : candid_none(),
        bracket_id: value.bracket_id,
        manual_close_applied: value.manual_close_applied,
        closure_type: to_candid_ClosureType_n24(_uploadFile, _downloadFile, value.closure_type)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    text: null;
} | {
    select: null;
} | {
    toggle: null;
} | {
    number: null;
} {
    return value == PropertyType.text ? {
        text: null
    } : value == PropertyType.select ? {
        select: null
    } : value == PropertyType.toggle ? {
        toggle: null
    } : value == PropertyType.number ? {
        number_: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClosureType): {
    take_profit: null;
} | {
    manual_close: null;
} | {
    stop_loss: null;
} | {
    break_even: null;
} {
    return value == ClosureType.take_profit ? {
        take_profit: null
    } : value == ClosureType.manual_close ? {
        manual_close: null
    } : value == ClosureType.stop_loss ? {
        stop_loss: null
    } : value == ClosureType.break_even ? {
        break_even: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalculationMethod): {
    tick: null;
} | {
    point: null;
} {
    return value == CalculationMethod.tick ? {
        tick: null
    } : value == CalculationMethod.point ? {
        point: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CustomProperty>): Array<_CustomProperty> {
    return value.map((x)=>to_candid_CustomProperty_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FilledBracketGroup>): Array<_FilledBracketGroup> {
    return value.map((x)=>to_candid_FilledBracketGroup_n22(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
